DB:
  mysql:
    address: 119.91.133.80
    port: 3306
    user_name: "root"
    password: "123456"
    database: "visualization_chart"
    db_table: "file_name"

App:
  name: visualization_chart
  host: 127.0.0.1
  port: 8989
